### ISSUE TITLE
dependency question

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/deepin-icon-theme#7]
Hi all! :)
Currently the Archlinux **deepin-icon-theme** package depends on both **faenza-icon-theme** and **flattr-icon-theme**.
My question is, are they really all needed? Could they maybe become at least opt depends, @felixonmars ?
I see ``Inherits=Flattr`` in **index.theme**, but also that I wonder if it is really necessary?

**Comment by shule1987** [comment]
hi,
Deepin icon theme don't need faenza-icon-theme and flattr-icon-theme any more, it has fully icons support, if some icons are missing , you are welcome to report to us.

**Comment by oberon2007** [comment]
Great news! 👍 So can you remove them please, @felixonmars?

**Comment by felixonmars** [comment]
Is it okay to remove the `Inherits=Flattr` line in index.theme now?

**Comment by wangxa** [comment]
According to my experience, you have to keep `Inherits=Flattr`; otherwise, the missing icons will be replaced by those coming from `hicolor` icon theme. It seems deepin icon theme is not designed for supporting Gnome 3.20+, because of lots of missing icons. See my pictures under Gnome of Fedora 25 ,after disabling `Inherits=Flattr`.

![screenshot from 2017-04-13 11-53-43](https://cloud.githubusercontent.com/assets/1250269/25002032/20457090-2040-11e7-91b4-6c75429eac32.png)

![screenshot from 2017-04-13 11-53-56](https://cloud.githubusercontent.com/assets/1250269/25002036/249d2af2-2040-11e7-8099-e8aed5483512.png)

![screenshot from 2017-04-13 11-54-03](https://cloud.githubusercontent.com/assets/1250269/25002043/2ba8f10a-2040-11e7-8329-efbb0724d437.png)


I just wondered why not see how the other beautiful icon theme projects, like `Paper icon theme`, `Acr icon theme`, and `Papirus icon theme` are designed.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
